print('\nMultiplicador')
n = int(input('\nInsira um valor da tabuada: '))

x1 = (n * 1)
x2 = (n * 2)
x3 = (n * 3)
x4 = (n * 4)
x5 = (n * 5)
x6 = (n * 6)
x7 = (n * 7)
x8 = (n * 8)
x9 = (n * 9)
x10 = (n * 10)

print('\nMultiplicador {}!'.format(n))
print( '==========================')
print(' 1 x {:2} = {}'.format(n, x1))
print(' 2 x {:2} = {}'.format(n, x2))
print(' 3 x {:2} = {}'.format(n, x3))
print(' 4 x {:2} = {}'.format(n, x4))
print(' 5 x {:2} = {}'.format(n, x5))
print(' 6 x {:2} = {}'.format(n, x6))
print(' 7 x {:2} = {}'.format(n, x7))
print(' 8 x {:2} = {}'.format(n, x8))
print(' 9 x {:2} = {}'.format(n, x9))
print('10 x {} = {}'.format(n, x10))
print( '==========================')